config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "meetups#index"
  resources :meetups do
  	resources :posts
  end
  
  namespace :api, :defaults => { :format => :json } do
  	namespace :v1 do

  		post "/signup" => "auth#signup"
  		post "/login" => "auth#login"
  		post "/logout" => "auth#logout"
  		get "/meetups" => "meetups#index"
  	end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meetup.rb
class Meetup < ApplicationRecord
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :meetup
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  before_create :generate_authentication_token

  def generate_authentication_token
  	self.authentication_token = Devise.friendly_token
  end
  
end

app/controllers/api/v1/auth_controller.rb
class Api::V1::AuthController < ApiController
	before_action :authenticate_user!, only: [:logout]
	              # 退出时验证是否是使用者

	def signup
		user = User.new( :email => params[:email], :password => params[:password] )
        
        if user.save
        	render :json => { :user_id => user.id }
        else
        	render :json => { :message => "Failed", :errors => user.errors },
        	:status => 400
        end
	end

	def login
		if params[:email] && params[:password]       # 先确保邮箱和密码都填写了才进一步查询
		   user = User.find_by_email(params[:email])
	    end
          
            # 我们不能直接用： user.password == params[:password]去判断，因为user的密码是查不出来的，为nil
		if user && user.valid_password?( params[:password])
			render :json => { :message => "Ok",
			                  :auth_token => user.authentication_token,
			                  :user_id => user.id }
		else
			render :json => { :message => "Email or Password is wrong"},
			:status => 401
		end
	end

	def logout
		current_user.generate_authentication_token # 重新产生token号，让之前的号失效
		current_user.save!
        
		render :json => { :message => "Ok"}
	end

end

app/controllers/api/v1/meetups_controller.rb
class Api::V1::MeetupsController < ApiController
   
    def index
    	@meetups = Meetup.all

        # 需要注意：这里不能用循环去 render :json，因为只能导一次
    	render :json => {
    		:data => @meetups.map { |meetup|
              {
              	:meetup_title => meetup.title,
    		    :meetup_description => meetup.description 
              }
    		}
    	}
    end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base

	before_action :authenticate_user_from_token!

	def authenticate_user_from_token!
		
		if params[:auth_token].present?
			user = User.find_by_authentication_token( params[:auth_token])

			# sign_in 是 devise的方法
			sign_in(user, store: false) if user
		end
	end
	# authenticate_user_from_token!用于接受auth_token参数，如果有会尝试登陆
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
    before_action :authenticate_user!, :only => [:create]
    
	def index
		@meetups = Meetup.all
	end

	def show
		@meetup = Meetup.find(params[:id])
		@post = Post.new
	end

	def new
		@meetup = Meetup.new
	end

	def create
		@meetup = Meetup.new(params_meetup)
	    if @meetup.save
           redirect_to meetups_path
           flash[:notice] = "#{@meetup.title}活动创建成功"
        else
           render new	    	
	    end
	end

	private

	def params_meetup
		params.require(:meetup).permit(:title,:description)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, :only => [:create]
    
	def create
		@meetup = Meetup.find(params[:meetup_id])
		@post = Post.new(params_post)
        @post.meetup = @meetup
        if @post.save
        	redirect_to meetup_path(@meetup)
        end
	end

	private

	def params_post
		params.require(:post).permit(:content)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		flash[:alert] = "亲，您好！"
	end
end

app/helpers/api/v1/auth_helper.rb
module Api::V1::AuthHelper
end

app/helpers/api/v1/meetups_helper.rb
module Api::V1::MeetupsHelper
end

app/helpers/api_helper.rb
module ApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper

	FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

	def flash_class(key)
		FLASH_CLASSES.fetch key.to_sym, key
	end

	def user_facing_flashes
		flash.to_hash.slice "alert", "notice", "warning"
	end

end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismisable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">x</button>    	
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default">
  <h4 style="margin-left: 20px;float: left;">欢迎来到meetups_demo!</h4>
  <% if current_user %>
  <div style="float: right;margin-top: 10px;">
    <%= current_user.email %>您好！
    <%= link_to("退出", destroy_user_session_path, method: :delete,class: "btn btn-primary btn-default") %>
  <% else %>
    <div style="float: right;margin-top: 10px;"><%= link_to("注册", new_user_registration_path) %>
    <%= link_to("登录", new_user_session_path) %>
    </div>
    <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetupsDemo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid">
    <%= render "common/navbar" %>
    <%= render "common/flashes" %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/meetups/index.html.erb
<h3 style="text-align: center">meetup活动一览表</h3>
<%= link_to("发表meetup", new_meetup_path, :class => "pull-right") %>
<hr>
<div>
<table class="table">
	<thead>
		<tr>
			<th>活动名称</th>
			<th>活动介绍</th>
			<th>评论条数</th>
		</tr>
	</thead>
	<tbody>
		<% @meetups.each do |meetup| %>
		<tr>
			<td><%= link_to(meetup.title, meetup_path(meetup)) %></td>
			<td><%= meetup.description %></td>
			<td><%= meetup.posts.count %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>

app/views/meetups/new.html.erb
<div class="col-md-4 col-md-offset-4">
<h3 style="margin-bottom: 40px;"> meetup活动创建 </h3>
  <%= form_for @meetup do |f| %>

    <%= f.label :"title"%>
    <%= f.text_field :title %>
    <br>
    <br>
    <%= f.label :description%>
    <br>
    <%= f.text_area :description %>
    <br>
    <%= f.submit "Submit", :disable_with => "Submiting..." %>
  <% end %>
</div>

app/views/meetups/show.html.erb
<div class="col-md-8 col-md-offset-2">
<h3>这里是<%= @meetup.title %>地带！</h3>

<% @meetup.posts.each_with_index do |post,i| %>
	  第<%= i+1 %>楼 
     <p><%= post.content %></p>
      <br>
    <% end %>
	<h4>meetup评论</h4>
    <%= form_for [@meetup,@post]  do |f| %>
    <h4><%= f.label :content %></h4>
    <%= f.text_area :content %>
    <br>
    <%= f.submit "Submit", :disable_with => "Submiting..." %>
    <% end %>
</div>

app/views/welcome/index.html.erb
Hello Word